//保存一些跨文件的常量
//左侧菜单
export const CHANGE_LEFTNAV_STATE = 'CHANGE_LEFTNAV_STATE';

//获取数据
//正在上映的电影
export const FETCH_NOW_PLAYING_SUCCESS = 'FETCH_NOW_PLAYING_SUCCESS';

//即将上映的电影
export const FETCH_COMMING_SOON_SUCCESS = 'FETCH_COMMING_SOON_SUCCESS';
//轮播
export const FETCH_BILLBOARD_SUCCESS = 'FETCH_BILLBOARD_SUCCESS';
//详情
export const FETCH_DETAIL_SUCCESS = 'FETCH_DETAIL_SUCCESS';
//影院正在上映
export const FETCH_FILME_NOW_SUCCESS = 'FETCH_FILME_NOW_SUCCESS';